##Spring Configuration
server:
  port: 8125
  servlet:
    context-path: /
spring:
  jpa:
    generate-ddl: false
    hibernate:
      use-new-id-generator-mappings: true
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        jdbc:
          batch_size: 10
          lob:
            non_contextual_creation: true
        order_inserts: true
        order_updates: true
        hbm2ddl:
          auto: none
    show-sql: true
  application:
    name: user-manager
  devtools:
    add-properties: false
  jdbc:
    initialize-schema: always
  job:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
