##DB
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
    sqlScriptEncoding: UTF-8
  jpa:
    show-sql: true
h2:
  console:
    enabled: true

jpa:
  generate-ddl: false
  database-platform: org.hibernate.dialect.H2Dialect
  hibernate:
    ddl-auto: none

